#!/bin/bash
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$REPO_DIR/.config"
SHELL_NAME=$(basename "$SHELL")
RCFILE="$HOME/.${SHELL_NAME}rc"

#===============================================================================
# 软链接管理工具函数
#===============================================================================

# 创建软链接，自动备份已存在的文件/目录
# Usage: safe_symlink <源路径> <目标路径>
safe_symlink() {
  local src="$1"
  local dst="$2"

  if [ ! -e "$src" ]; then
    echo "❌ 源不存在: $src"
    return 1
  fi

  # 如果目标已存在
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    # 如果已经是正确的软链接，跳过
    if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
      echo "✅ 已链接: $dst -> $src"
      return 0
    fi

    # 备份旧文件
    local backup="${dst}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "⚠️  备份已存在的文件: $dst -> $backup"
    mv "$dst" "$backup"
  fi

  # 创建软链接
  ln -s "$src" "$dst"
  echo "🔗 链接创建: $dst -> $src"
}

# 递归链接源目录下的所有文件到目标目录（保留目录结构）
# Usage: link_files_recursive <源目录> <目标目录>
link_files_recursive() {
  local src_dir="${1%/}"
  local dst_dir="${2%/}"

  if [ ! -d "$src_dir" ]; then
    echo "❌ 源目录不存在: $src_dir"
    return 1
  fi

  mkdir -p "$dst_dir"

  while IFS= read -r -d '' src_file; do
    local rel_path="${src_file#$src_dir/}"
    local dst_file="$dst_dir/$rel_path"
    local dst_parent
    dst_parent="$(dirname "$dst_file")"
    mkdir -p "$dst_parent"
    safe_symlink "$src_file" "$dst_file"
  done < <(find "$src_dir" -type f -print0)
}

#===============================================================================
# 主配置流程
#===============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  dotfiles 配置工具"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# 1. 链接 .claude 目录（逐个文件链接，保留 history/memory）
if [ -d "$REPO_DIR/.claude" ]; then
  echo "━━━ 配置 .claude ━━━"
  link_files_recursive "$REPO_DIR/.claude" "$HOME/.claude"
  echo
fi

# 2. 链接 .config 目录内容
if [ -d "$CONFIG_DIR" ]; then
  echo "━━━ 配置 .config ━━━"
  link_files_recursive "$CONFIG_DIR" "$HOME/.config"
  echo
fi

# 3. 配置 shell rc 文件
echo "━━━ 配置 shell rc ━━━"
if grep -q "Generated by dotfiles run_config.sh" "$RCFILE" 2>/dev/null; then
  echo "✅ 已配置，跳过 rc 文件修改"
else
  cat <<EOF >>"$RCFILE"

# Generated by dotfiles run_config.sh
source $REPO_DIR/shell/settings.sh
source $REPO_DIR/shell/aliases.sh
source $REPO_DIR/shell/funcs.sh
if [ "\$(basename \$SHELL)" = zsh ]; then
	source $REPO_DIR/zsh/vi.zsh
fi
EOF
  echo "✅ 已追加配置到 $RCFILE"
fi
echo

# 4. 完成配置
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ 配置完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "运行以下命令应用 shell 配置："
echo "  source $RCFILE"
