#!/bin/bash

set -eu

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$REPO_DIR/config"
SHELL_NAME=$(basename "$SHELL")
RCFILE="$HOME/.${SHELL_NAME}rc"

#===============================================================================
# .env 文件检查与加载
#===============================================================================
ENV_FILE="$REPO_DIR/.env"

check_env_file() {
  if [ ! -f "$ENV_FILE" ]; then
    echo "❌ .env 文件不存在: $ENV_FILE"
    return 1
  fi

  local has_empty=0

  # 读取每一行，检查环境变量赋值
  while IFS= read -r line; do
    # 跳过注释和空行
    if [[ "$line" =~ ^[[:space:]]*# ]] || [[ "$line" =~ ^[[:space:]]*$ ]]; then
      continue
    fi

    # 匹配 KEY=value 格式
    if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local value="${BASH_REMATCH[2]}"

      # 去掉 value 首尾空白
      value="${value#"${value%%[![:space:]]*}"}"
      value="${value%"${value##*[![:space:]]}"}"

      # 移除 value 周围的引号
      value="${value%\"}"
      value="${value#\"}"
      value="${value%\'}"
      value="${value#\'}"

      if [ -z "$value" ]; then
        echo "❌ 发现空变量: $key"
        has_empty=1
      fi
    fi
  done < "$ENV_FILE"

  if [ "$has_empty" -eq 1 ]; then
    echo
    echo "❌ .env 文件中存在空变量，请先填写所有变量值"
    return 1
  fi

  return 0
}

# 检查并加载 .env
echo "━━━ 检查 .env 文件 ━━━"
if check_env_file; then
  # shellcheck source=/dev/null
  # source "$ENV_FILE"
  set -a
  source .env
  set +a
  echo "✅ .env 文件加载成功"
else
  exit 1
fi
echo

#===============================================================================
# 软链接管理工具函数
#===============================================================================

# 创建软链接，自动备份已存在的文件/目录
# Usage: safe_symlink <源路径> <目标路径>
resolve_existing_path() {
  local path="$1"
  local dir
  dir="$(cd "$(dirname "$path")" && pwd -P)" || return 1
  echo "$dir/$(basename "$path")"
}

resolve_symlink_target() {
  local link_path="$1"
  local target
  local base_dir

  target="$(readlink "$link_path")" || return 1
  if [[ "$target" = /* ]]; then
    resolve_existing_path "$target"
    return 0
  fi

  base_dir="$(cd "$(dirname "$link_path")" && pwd -P)" || return 1
  resolve_existing_path "$base_dir/$target"
}

safe_symlink() {
  local src="$1"
  local dst="$2"
  local src_resolved
  local dst_resolved
  local dst_parent

  if [ ! -e "$src" ]; then
    echo "❌ 源不存在: $src"
    return 1
  fi

  src_resolved="$(resolve_existing_path "$src")" || {
    echo "❌ 无法解析源路径: $src"
    return 1
  }

  dst_parent="$(dirname "$dst")"
  mkdir -p "$dst_parent"

  # 如果目标已存在
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    # 如果已经是正确的软链接，跳过
    if [ -L "$dst" ]; then
      dst_resolved="$(resolve_symlink_target "$dst" 2>/dev/null)" || dst_resolved=""
    else
      dst_resolved=""
    fi
    if [ -n "$dst_resolved" ] && [ "$dst_resolved" = "$src_resolved" ]; then
      echo "✅ 已链接: $dst -> $src"
      return 0
    fi

    # 备份旧文件
    local backup="${dst}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "⚠️  备份已存在的文件: $dst -> $backup"
    mv "$dst" "$backup"
  fi

  # 创建软链接
  ln -s "$src" "$dst"
  echo "🔗 链接创建: $dst -> $src"
}

# 递归链接源目录下的所有文件到目标目录（保留目录结构）
# Usage: link_files_recursive <源目录> <目标目录>
link_files_recursive() {
  local src_dir="${1%/}"
  local dst_dir="${2%/}"

  if [ ! -d "$src_dir" ]; then
    echo "❌ 源目录不存在: $src_dir"
    return 1
  fi

  mkdir -p "$dst_dir"

  while IFS= read -r -d '' src_file; do
    local rel_path="${src_file#$src_dir/}"
    local dst_file="$dst_dir/$rel_path"
    local dst_parent
    dst_parent="$(dirname "$dst_file")"
    mkdir -p "$dst_parent"
    safe_symlink "$src_file" "$dst_file"
  done < <(find "$src_dir" -type f -print0)
}

#===============================================================================
# 主配置流程
#===============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  dotfiles 配置工具"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# 1. 配置 AI 相关

# 1.1 claude
mkdir -p "$HOME/.claude"
safe_symlink "$REPO_DIR/ai/claude/settings.json" "$HOME/.claude/settings.json"
safe_symlink "$REPO_DIR/ai/prompts/coding_system.md" "$HOME/.claude/CLAUDE.md"
link_files_recursive "$REPO_DIR/ai/skills" "$HOME/.claude/skills"


# 1.2 codex
mkdir -p "$HOME/.codex"
mkdir -p "$HOME/.agents"
safe_symlink "$REPO_DIR/ai/codex/config.toml" "$HOME/.codex/config.toml"
safe_symlink "$REPO_DIR/ai/prompts/coding_system.md" "$HOME/.codex/AGENTS.md"
link_files_recursive "$REPO_DIR/ai/skills" "$HOME/.agents/skills"



# 2. 配置 zed、uv etc.
echo "━━━ 配置 .config ━━━"
link_files_recursive "$REPO_DIR/zed" "$HOME/.config/zed"
safe_symlink "$REPO_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"
echo

# 3. 配置 shell rc 文件
echo "━━━ 配置 shell rc ━━━"
if grep -q "Generated by dotfiles run_config.sh" "$RCFILE" 2>/dev/null; then
  echo "✅ 已配置，跳过 rc 文件修改"
else
  cat <<EOF >>"$RCFILE"

# Generated by adenialzz/dotfiles run_config.sh
source $REPO_DIR/shell/settings.sh
source $REPO_DIR/shell/alias/shell-base.sh
source $REPO_DIR/shell/alias/git.sh
source $REPO_DIR/shell/alias/tmux.sh
source $REPO_DIR/shell/alias/coding-agents.sh
source $REPO_DIR/shell/funcs.sh
if [ "\$(basename \$SHELL)" = zsh ]; then
	source $REPO_DIR/shell/vi.zsh
fi
EOF
  echo "✅ 已追加配置到 $RCFILE"
fi
echo

# 4. 完成配置
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ 配置完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "运行以下命令应用 shell 配置："
echo "  source $RCFILE"
