#!/bin/bash

set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SHELL_NAME=$(basename "$SHELL")
RCFILE="$HOME/.${SHELL_NAME}rc"
case "$SHELL_NAME" in
  bash|zsh) ;;
  *) echo "当前仅支持 Bash 和 Zsh"; exit 1 ;;
esac

#===============================================================================
# 软链接管理工具函数
#===============================================================================

# 创建软链接，自动备份已存在的文件/目录
# Usage: safe_symlink <源路径> <目标路径>
resolve_existing_path() {
  local path="$1"
  local dir
  dir="$(cd "$(dirname "$path")" && pwd -P)" || return 1
  echo "$dir/$(basename "$path")"
}

resolve_symlink_target() {
  local link_path="$1"
  local target
  local base_dir

  target="$(readlink "$link_path")" || return 1
  if [[ "$target" = /* ]]; then
    resolve_existing_path "$target"
    return 0
  fi

  base_dir="$(cd "$(dirname "$link_path")" && pwd -P)" || return 1
  resolve_existing_path "$base_dir/$target"
}

safe_symlink() {
  local src="$1"
  local dst="$2"
  local src_resolved
  local dst_resolved
  local dst_parent

  if [ ! -e "$src" ]; then
    echo "❌ 源不存在: $src"
    return 1
  fi

  src_resolved="$(resolve_existing_path "$src")" || {
    echo "❌ 无法解析源路径: $src"
    return 1
  }

  dst_parent="$(dirname "$dst")"
  mkdir -p "$dst_parent"

  # 如果目标已存在
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    # 如果已经是正确的软链接，跳过
    if [ -L "$dst" ]; then
      dst_resolved="$(resolve_symlink_target "$dst" 2>/dev/null)" || dst_resolved=""
    else
      dst_resolved=""
    fi
    if [ -n "$dst_resolved" ] && [ "$dst_resolved" = "$src_resolved" ]; then
      echo "✅ 已链接: $dst -> $src"
      return 0
    fi

    # 备份旧文件
    local backup="${dst}.backup.$(date +%Y%m%d_%H%M%S)"
    echo "⚠️  备份已存在的文件: $dst -> $backup"
    mv "$dst" "$backup"
  fi

  # 创建软链接
  ln -s "$src" "$dst"
  echo "🔗 链接创建: $dst -> $src"
}

# 递归链接源目录下的所有文件到目标目录（保留目录结构）
# Usage: link_files_recursive <源目录> <目标目录>
link_files_recursive() {
  local src_dir="${1%/}"
  local dst_dir="${2%/}"

  if [ ! -d "$src_dir" ]; then
    echo "❌ 源目录不存在: $src_dir"
    return 1
  fi

  mkdir -p "$dst_dir"

  while IFS= read -r -d '' src_file; do
    local rel_path="${src_file#$src_dir/}"
    local dst_file="$dst_dir/$rel_path"
    local dst_parent
    dst_parent="$(dirname "$dst_file")"
    mkdir -p "$dst_parent"
    safe_symlink "$src_file" "$dst_file"
  done < <(find "$src_dir" -type f -print0)
}

link_skills() {
  local skill_dir
  for skill_dir in "$REPO_DIR/ai/skills/"*/; do
    [ -f "$skill_dir/SKILL.md" ] || continue
    safe_symlink "${skill_dir%/}" "$1/$(basename "$skill_dir")"
  done
}

configure_shell_rc() {
  local entry="source \"$REPO_DIR/shell/init.sh\""
  local staged
  staged="$(mktemp)"
  touch "$RCFILE"
  if ! awk -v entry="$entry" '
    /^# Generated by (adenialzz\/)?dotfiles run_config.sh$/ { skipping = 1; next }
    skipping { if ($0 == "fi") skipping = 0; next }
    $0 != entry { print }
    END { if (skipping) exit 1; print entry }
  ' "$RCFILE" > "$staged"; then
    rm "$staged"
    echo "旧 Shell 初始化块不完整，请检查 $RCFILE"
    return 1
  fi
  if cmp -s "$RCFILE" "$staged"; then
    echo "✅ Shell 入口已配置"
  else
    local backup="${RCFILE}.backup.$(date +%Y%m%d_%H%M%S)"
    cp -p "$RCFILE" "$backup"
    cat "$staged" > "$RCFILE"
    echo "✅ Shell 入口已更新，原文件备份到 $backup"
  fi
  rm "$staged"
}

#===============================================================================
# 主配置流程
#===============================================================================

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  dotfiles 配置工具"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo

# 1. 配置 AI 相关

# 1.1 claude
mkdir -p "$HOME/.claude"
safe_symlink "$REPO_DIR/ai/claude/settings.json" "$HOME/.claude/settings.json"
safe_symlink "$REPO_DIR/ai/prompts/coding_system.md" "$HOME/.claude/CLAUDE.md"
link_skills "$HOME/.claude/skills"


# 1.2 codex
mkdir -p "$HOME/.codex"
mkdir -p "$HOME/.agents"
safe_symlink "$REPO_DIR/ai/codex/config.toml" "$HOME/.codex/config.toml"
safe_symlink "$REPO_DIR/ai/codex/deepseek.config.toml" "$HOME/.codex/deepseek.config.toml"
safe_symlink "$REPO_DIR/ai/codex/deepseek-models.json" "$HOME/.codex/deepseek-models.json"
safe_symlink "$REPO_DIR/ai/prompts/coding_system.md" "$HOME/.codex/AGENTS.md"
link_skills "$HOME/.agents/skills"



# 2. 配置 zed、uv etc.
echo "━━━ 配置 .config ━━━"
link_files_recursive "$REPO_DIR/zed" "$HOME/.config/zed"
safe_symlink "$REPO_DIR/uv/uv.toml" "$HOME/.config/uv/uv.toml"
safe_symlink "$REPO_DIR/shell/bin" "$HOME/.config/.mbin"
safe_symlink "$REPO_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"
echo

# 3. 配置 shell rc 文件
echo "━━━ 配置 shell rc ━━━"
configure_shell_rc
echo

# 4. 完成配置
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ 配置完成！"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "运行以下命令应用 shell 配置："
echo "  source $RCFILE"
