model = "gpt-5.4"

# sandbox_mode = "danger-full-access"
# approval_policy = "never"

allow_login_shell = false

[shell_environment_policy]
inherit = "all"
exclude = ["http_proxy", "https_proxy", "HTTP_PROXY", "HTTPS_PROXY"]


[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
