unbind C-b
set -g prefix C-w
bind C-w send-prefix

# 新建pane（分屏）
unbind '"'
unbind %
bind v split-window -v
bind s split-window -h

# pane 移动
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
