unbind C-b
set -g prefix C-w
bind C-w send-prefix

# 新建pane（分屏）
unbind '"'
unbind %
bind v split-window -v
bind s split-window -h

# pane 移动
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 调整 pane 大小
bind -n M-h resize-pane -L 3
bind -n M-j resize-pane -D 3
bind -n M-k resize-pane -U 3
bind -n M-l resize-pane -R 3


# mouse 主要是解决滚轮？j
set -g mouse on

# 刷新 conf 文件 Prefix + r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# 避免按 Esc 后得等一会儿（看有没有后续其他键），导致 vi zsh 进 normal mode 太慢
set -sg escape-time 0

# 修改 $TERM，3.2a version 默认是 screen？
set -g default-terminal "tmux-256color"

# 透传 zed 的 terminal 跳转超链接的能力
set -ga terminal-features ",*:hyperlinks"
set -g allow-passthrough on


